version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: backend_fullstack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: backend_fullstack
      DB_PORT: 5432
      DB_SSLMODE: disable
      JWT_SECRET_KEY: your_secret_key
    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  db_data: